ajout d'users pour les clients
F-Jean/BileMo pull request #17
Opened 2022-04-13 15:11 UTC by F-Jean

2022-04-18 09:30 UTC, F-Jean commented
pas besoin de references (fixtures pas détaillées, pas pertinent dans les cas futurs) un findAll est suffisant

2022-05-02 09:22 UTC, TBoileau requested changes

2022-05-02 09:22 UTC, TBoileau commented on src/Entity/User.php
> +        ]
Inutile

2022-05-02 09:22 UTC, TBoileau commented on src/Entity/User.php
> +        'delete',
Il manque la partie autorisation.
https://api-platform.com/docs/core/security/#security

2022-05-06 15:08 UTC, merged